### ISSUE TITLE
[Documentation] Start writing the documentation

### ISSUE THREAD

**Issue by pzarabadip** [pzarabadip/aiida-catmat#14]
As we are getting closer to a properly stable version of workchain and more will be added, I need to start adding the documentations. I'll do it using `sphnix` so once we are at the stage of making codes public, we can simply deploy the docs to `readthedocs`.
- [ ] proper docstrings in `rst` for API documentation
- [ ] Pages to describe technical considerations
- [ ] Tutorials for both preparing structures, protocols, and running workchains
- [ ] Tutorials for query

**Comment by ezpzbz** [comment]
It is done now.
